[package]
name = "gatha-transcribe"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.8", features = ["macros"] }
serde = "1.0.228"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
utoipa = "5.4.0"
utoipa-axum = "0.2"
